title: Carlos Segura
logo: "/images/thumbnail.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Backend Python Developer
  <br><br>
  About:
  <br>
  I am a hacker, creative-thinker and have a particular interest in natural-language-processing and machine-learning. While NLP is my pursuit - I love working on new domains where creative problem solving is needed.
  <br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
